package Proses;

import KomponenGUI.FDateF;
import static KomponenGUI.FDateF.datetostr;
import LSubProces.DRunSelctOne;
import LSubProces.Insert;
import LSubProces.RunSelct;
import LSubProces.Update;
import Master.MasterKaryawan;
import javax.swing.JOptionPane;
import java.awt.event.KeyEvent;
import static java.lang.Integer.parseInt;
import static java.lang.System.out;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DecimalFormat;
import java.text.NumberFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author Martono
 */
public class BarangKeluar extends javax.swing.JFrame {

    KomponenGUI.JtextF[] arrayBarang;
    String idEdit, jenisBarang, kategoriBarang, namaBarang, jumlahBarangKeluar;
    String[] idDetailBarangMasuk;

    /**
     * Creates new form BarangKeluar
     */
    public BarangKeluar(Object id) {
        initComponents();
        setLocationRelativeTo(null);
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        idEdit = id.toString();
        if (idEdit.equals("0")) {
            setTitle("Tambah Barang Keluar");
            setNomorBarangKeluar();
            JBUbah.setVisible(false);
        } else {
            setTitle("Ubah Barang Keluar");
            loadData();
            JBTambah.setVisible(false);
            JBTambahTutup.setVisible(false);
        }
        setVisible(true);
        JCNamaPemakai.requestFocus();
        arrayBarang = new KomponenGUI.JtextF[]{JTJenisBarang, JTKategoriBarang, JTNamaBarang};
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JLNomorBarangKeluar = new KomponenGUI.JlableF();
        JLNomoBarangKeluar2 = new KomponenGUI.JlableF();
        JTNomorBarangKeluar = new KomponenGUI.JtextF();
        JLTanggalBarangKeluar = new KomponenGUI.JlableF();
        JLTanggalBarangKeluar2 = new KomponenGUI.JlableF();
        JDTanggalBarangKeluar = new KomponenGUI.JdateCF();
        JLNamaPemakai = new KomponenGUI.JlableF();
        JLNamaPemakai2 = new KomponenGUI.JlableF();
        JCNamaPemakai = new KomponenGUI.JcomboboxF();
        JBNamaPemakai = new KomponenGUI.JbuttonF();
        JLJenisBarang = new KomponenGUI.JlableF();
        JLJenisBarang2 = new KomponenGUI.JlableF();
        JTJenisBarang = new KomponenGUI.JtextF();
        JLKategoriBarang = new KomponenGUI.JlableF();
        JLKategoriBarang2 = new KomponenGUI.JlableF();
        JTKategoriBarang = new KomponenGUI.JtextF();
        JLNamaBarang = new KomponenGUI.JlableF();
        JLNamaBarang2 = new KomponenGUI.JlableF();
        JTNamaBarang = new KomponenGUI.JtextF();
        JLCariBarang = new KomponenGUI.JlableF();
        JLCariBarang2 = new KomponenGUI.JlableF();
        JTCariBarang = new KomponenGUI.JtextF();
        JBCariBarang = new KomponenGUI.JbuttonF();
        JLStokBarang = new KomponenGUI.JlableF();
        JLStokBarang2 = new KomponenGUI.JlableF();
        JRStokBarang = new KomponenGUI.JRibuanTextField();
        JLJumlahBarangKeluar = new KomponenGUI.JlableF();
        JLJumlahBarangKeluar2 = new KomponenGUI.JlableF();
        JRJumlahBarangKeluar = new KomponenGUI.JRibuanTextField();
        JLSerialNumber = new KomponenGUI.JlableF();
        JLSerialNumber2 = new KomponenGUI.JlableF();
        JCSerialNumber = new KomponenGUI.JcomboboxF();
        JLKeterangan = new KomponenGUI.JlableF();
        JLKeterangan2 = new KomponenGUI.JlableF();
        JSPKeterangan = new javax.swing.JScrollPane();
        JTKeterangan = new KomponenGUI.JTextAreaF();
        JBKembali = new KomponenGUI.JbuttonF();
        JBTambah = new KomponenGUI.JbuttonF();
        JBTambahTutup = new KomponenGUI.JbuttonF();
        JBUbah = new KomponenGUI.JbuttonF();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        JLNomorBarangKeluar.setText("Nomor Barang Keluar");

        JLNomoBarangKeluar2.setText(":");

        JTNomorBarangKeluar.setEnabled(false);

        JLTanggalBarangKeluar.setText("Tanggal Barang Keluar");

        JLTanggalBarangKeluar2.setText(":");

        JDTanggalBarangKeluar.setDate(new Date());
        JDTanggalBarangKeluar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                JDTanggalBarangKeluarKeyReleased(evt);
            }
        });

        JLNamaPemakai.setText("Nama Pemakai");

        JLNamaPemakai2.setText(":");

        JCNamaPemakai.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-- Pilih Nama Pemakai --" }));
        JCNamaPemakai.load("SELECT '-- Pilih Nama Pemakai --' AS `NamaKaryawan` UNION SELECT `NamaKaryawan` FROM `tbmkaryawan`");
        JCNamaPemakai.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                JCNamaPemakaiKeyReleased(evt);
            }
        });

        JBNamaPemakai.setText("+");
        JBNamaPemakai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBNamaPemakaiActionPerformed(evt);
            }
        });

        JLJenisBarang.setText("Jenis Barang");

        JLJenisBarang2.setText(":");

        JTJenisBarang.setEnabled(false);

        JLKategoriBarang.setText("Kategori Barang");

        JLKategoriBarang2.setText(":");

        JTKategoriBarang.setEnabled(false);

        JLNamaBarang.setText("Nama Barang");

        JLNamaBarang2.setText(":");

        JTNamaBarang.setEnabled(false);

        JLCariBarang.setText("Cari Barang");

        JLCariBarang2.setText(":");

        JTCariBarang.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                JTCariBarangKeyReleased(evt);
            }
        });

        JBCariBarang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resource/Search.png"))); // NOI18N
        JBCariBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBCariBarangActionPerformed(evt);
            }
        });

        JLStokBarang.setText("Stok Barang");

        JLStokBarang2.setText(":");

        JRStokBarang.setEnabled(false);

        JLJumlahBarangKeluar.setText("Jumlah Barang Keluar");

        JLJumlahBarangKeluar2.setText(":");

        JRJumlahBarangKeluar.setText("1");
        JRJumlahBarangKeluar.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                JRJumlahBarangKeluarFocusGained(evt);
            }
        });
        JRJumlahBarangKeluar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                JRJumlahBarangKeluarKeyPressed(evt);
            }
        });

        JLSerialNumber.setText("Serial Number");

        JLSerialNumber2.setText(":");

        JCSerialNumber.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-- Pilih Serial Number --" }));
        JCSerialNumber.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                JCSerialNumberKeyReleased(evt);
            }
        });

        JLKeterangan.setText("Keterangan");

        JLKeterangan2.setText(":");

        JTKeterangan.setColumns(20);
        JTKeterangan.setLineWrap(true);
        JTKeterangan.setRows(5);
        JTKeterangan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                JTKeteranganKeyPressed(evt);
            }
        });
        JSPKeterangan.setViewportView(JTKeterangan);

        JBKembali.setText("Kembali");
        JBKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBKembaliActionPerformed(evt);
            }
        });

        JBTambah.setText("Tambah");
        JBTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBTambahActionPerformed(evt);
            }
        });

        JBTambahTutup.setText("Tambah dan Tutup");
        JBTambahTutup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBTambahTutupActionPerformed(evt);
            }
        });

        JBUbah.setText("Ubah");
        JBUbah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBUbahActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(JLSerialNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JLSerialNumber2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JCSerialNumber, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(JLNamaPemakai, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(JLNomorBarangKeluar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(JLTanggalBarangKeluar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(JLTanggalBarangKeluar2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(JLNomoBarangKeluar2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(JTNomorBarangKeluar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(JDTanggalBarangKeluar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(JLNamaPemakai2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(JCNamaPemakai, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(JBNamaPemakai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(JLJumlahBarangKeluar, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE)
                                            .addComponent(JLStokBarang, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(JLCariBarang, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(JLNamaBarang, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(JLKategoriBarang, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(JLJenisBarang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(JLKeterangan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(JLJenisBarang2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(JLKategoriBarang2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(JLNamaBarang2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(JLCariBarang2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(JLStokBarang2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(JLJumlahBarangKeluar2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(JLKeterangan2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(JBKembali, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(JBTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(JBTambahTutup, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(JBUbah, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(JTCariBarang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(JBCariBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(JTKategoriBarang, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(JTNamaBarang, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(JRStokBarang, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(JRJumlahBarangKeluar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(JSPKeterangan, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(JTJenisBarang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(10, 10, 10))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JLNomorBarangKeluar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JLNomoBarangKeluar2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JTNomorBarangKeluar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(JLTanggalBarangKeluar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(JLTanggalBarangKeluar2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(JDTanggalBarangKeluar, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JLNamaPemakai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JLNamaPemakai2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JCNamaPemakai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JBNamaPemakai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JLJenisBarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JLJenisBarang2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JTJenisBarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JLKategoriBarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JLKategoriBarang2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JTKategoriBarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JLNamaBarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JLNamaBarang2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JTNamaBarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JBCariBarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(JLCariBarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(JLCariBarang2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(JTCariBarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JLStokBarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JLStokBarang2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JRStokBarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JLJumlahBarangKeluar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JLJumlahBarangKeluar2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JRJumlahBarangKeluar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JLSerialNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JLSerialNumber2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JCSerialNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JLKeterangan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JLKeterangan2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(JSPKeterangan, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JBTambahTutup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JBTambah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JBKembali, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JBUbah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JBTambahTutupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBTambahTutupActionPerformed
        tambah(true);
    }//GEN-LAST:event_JBTambahTutupActionPerformed

    private void JBTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBTambahActionPerformed
        tambah(false);
    }//GEN-LAST:event_JBTambahActionPerformed

    private void JBKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBKembaliActionPerformed
        dispose();
    }//GEN-LAST:event_JBKembaliActionPerformed

    private void JBCariBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBCariBarangActionPerformed
        cariBarang(null);
    }//GEN-LAST:event_JBCariBarangActionPerformed

    private void JDTanggalBarangKeluarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JDTanggalBarangKeluarKeyReleased
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            JCNamaPemakai.requestFocus();
        }
    }//GEN-LAST:event_JDTanggalBarangKeluarKeyReleased

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        if (idEdit.equals("0")) {
            GlobalVar.Var.tambahBarangKeluar = null;
        } else {
            GlobalVar.Var.editBarangKeluar = null;
        }
    }//GEN-LAST:event_formWindowClosed

    private void JTCariBarangKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JTCariBarangKeyReleased
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (JTCariBarang.getText().replace(" ", "").isEmpty()) {
                cariBarang(null);
            } else {
                JRJumlahBarangKeluar.requestFocus();
            }
        } else if (evt.getKeyCode() == KeyEvent.VK_SPACE) {
            cariBarang(null);
        } else if (isAlphaNumeric(String.valueOf(evt.getKeyChar()))) {
            cariBarang(JTCariBarang.getText());
        }
    }//GEN-LAST:event_JTCariBarangKeyReleased

    private void JRJumlahBarangKeluarFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_JRJumlahBarangKeluarFocusGained
        setStokBarang();
        JTCariBarang.setText("");
        loadSerialNumber("");
    }//GEN-LAST:event_JRJumlahBarangKeluarFocusGained

    private void JRJumlahBarangKeluarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JRJumlahBarangKeluarKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            JCSerialNumber.requestFocus();
        }
    }//GEN-LAST:event_JRJumlahBarangKeluarKeyPressed

    private void JCNamaPemakaiKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JCNamaPemakaiKeyReleased
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (JCNamaPemakai.getSelectedIndex() == 0) {
                JCNamaPemakai.showPopup();
            } else {
                JTCariBarang.requestFocus();
            }
        }
    }//GEN-LAST:event_JCNamaPemakaiKeyReleased

    private void JBNamaPemakaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBNamaPemakaiActionPerformed
        if (GlobalVar.Var.tambahMasterKaryawan == null) {
            GlobalVar.Var.tambahMasterKaryawan = new MasterKaryawan("0");
        } else {
            GlobalVar.Var.tambahMasterKaryawan.setState(NORMAL);
            GlobalVar.Var.tambahMasterKaryawan.toFront();
        }
    }//GEN-LAST:event_JBNamaPemakaiActionPerformed

    private void JBUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBUbahActionPerformed
        ubah();
    }//GEN-LAST:event_JBUbahActionPerformed

    private void JTKeteranganKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JTKeteranganKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            tambah(false);
        }
    }//GEN-LAST:event_JTKeteranganKeyPressed

    private void JCSerialNumberKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JCSerialNumberKeyReleased
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (JCSerialNumber.getSelectedIndex() == 0) {
                JCSerialNumber.showPopup();
            } else {
                JTKeterangan.requestFocus();
            }
        }
    }//GEN-LAST:event_JCSerialNumberKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BarangKeluar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BarangKeluar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BarangKeluar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BarangKeluar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BarangKeluar("0");
            }
        });
    }

    void setNomorBarangKeluar() {
        NumberFormat nf = new DecimalFormat("0000");
        String nomorTransaksi = null;
        RunSelct runSelct = new RunSelct();
        runSelct.setQuery("SELECT `NomorBarangKeluar` FROM `tbbarangkeluar` ORDER BY `NomorBarangKeluar` DESC LIMIT 1");
        try {
            ResultSet rs = runSelct.excute();
            if (!rs.isBeforeFirst()) {
                nomorTransaksi = "0001/" + datetostr(new Date(), "YY") + "/BK";
            }
            while (rs.next()) {
                String lastNomorTransaksi = rs.getString("NomorBarangKeluar");
                String subNomorTransaksi = lastNomorTransaksi.substring(0, 4);
                int generatedNumber = parseInt(subNomorTransaksi) + 1;
                if (generatedNumber == 9999 || Integer.valueOf(lastNomorTransaksi.substring(5, 7)) < Integer.valueOf(datetostr(new Date(), "YY"))) {
                    generatedNumber = 1;
                }
                nomorTransaksi = nf.format(generatedNumber) + "/" + datetostr(new Date(), "YY") + "/BK";
            }
        } catch (SQLException e) {
            out.println("E6" + e);
            JOptionPane.showMessageDialog(this, "Gagal Generate Nomor Barang Keluar", "Information", JOptionPane.INFORMATION_MESSAGE);
        } finally {
            runSelct.closecon();
        }
        JTNomorBarangKeluar.setText(nomorTransaksi);
    }

    boolean isAlphaNumeric(String str) {
        for (int i = 0; i < str.length(); i++) {
            char c = str.charAt(i);
            if (c < 0x30 || (c >= 0x3a && c <= 0x40) || (c > 0x5a && c <= 0x60) || c > 0x7a) {
                return false;
            }
        }
        return true;
    }

    void cariBarang(String keywordCari) {
        if (GlobalVar.Var.jCari == null) {
            GlobalVar.Var.jCari = new JCari("SELECT `JenisBarang` AS 'Jenis Barang', `KategoriBarang` AS 'Kategori Barang', `NamaBarang` AS 'Nama Barang' FROM `tbmbarang` AS A JOIN `tbmkategoribarang` AS B ON A.`IdKategoriBarang`=B.`IdKategoriBarang` JOIN `tbmjenisbarang` AS C ON B.`IdJenisBarang`=C.`IdJenisBarang` WHERE `JenisBarang` ", "SELECT `JenisBarang` AS 'Jenis Barang', `KategoriBarang` AS 'Kategori Barang', `NamaBarang` AS 'Nama Barang' FROM `tbmbarang` AS A JOIN `tbmkategoribarang` AS B ON A.`IdKategoriBarang`=B.`IdKategoriBarang` JOIN `tbmjenisbarang` AS C ON B.`IdJenisBarang`=C.`IdJenisBarang` WHERE `KategoriBarang` ", "SELECT `JenisBarang` AS 'Jenis Barang', `KategoriBarang` AS 'Kategori Barang', `NamaBarang` AS 'Nama Barang' FROM `tbmbarang` AS A JOIN `tbmkategoribarang` AS B ON A.`IdKategoriBarang`=B.`IdKategoriBarang` JOIN `tbmjenisbarang` AS C ON B.`IdJenisBarang`=C.`IdJenisBarang` WHERE `NamaBarang` ", "Cari Barang", arrayBarang, keywordCari, JRJumlahBarangKeluar, JTCariBarang);
        } else {
            GlobalVar.Var.jCari.setState(NORMAL);
            GlobalVar.Var.jCari.toFront();
        }
    }

    void setStokBarang() {
        if (!JTJenisBarang.getText().isEmpty() && !JTKategoriBarang.getText().isEmpty() && !JTNamaBarang.getText().isEmpty()) {
            DRunSelctOne dRunSelctOne = new DRunSelctOne();
            dRunSelctOne.seterorm("Gagal Menampilkan Data Stok Barang");
            dRunSelctOne.setQuery("SELECT SUM(`Stok`) AS 'Stok' FROM (SELECT IFNULL(SUM(`JumlahBarang`),0) AS 'Stok' FROM `tbbarangmasukdetail` WHERE `IdBarang`=(SELECT `IdBarang` FROM `tbmbarang` AS A JOIN `tbmkategoribarang` AS B ON A.`IdKategoriBarang`=B.`IdKategoriBarang` JOIN `tbmjenisbarang` AS C ON B.`IdJenisBarang`=C.`IdJenisBarang` WHERE `JenisBarang`='" + JTJenisBarang.getText() + "' AND `KategoriBarang`='" + JTKategoriBarang.getText() + "' AND `NamaBarang`='" + JTNamaBarang.getText() + "') UNION SELECT IFNULL(SUM(`JumlahBarang`)*-1,0) AS 'Stok' FROM `tbbarangkeluar` WHERE `IdBarang`=(SELECT `IdBarang` FROM `tbmbarang` AS A JOIN `tbmkategoribarang` AS B ON A.`IdKategoriBarang`=B.`IdKategoriBarang` JOIN `tbmjenisbarang` AS C ON B.`IdJenisBarang`=C.`IdJenisBarang` WHERE `JenisBarang`='" + JTJenisBarang.getText() + "' AND `KategoriBarang`='" + JTKategoriBarang.getText() + "' AND `NamaBarang`='" + JTNamaBarang.getText() + "') UNION SELECT IFNULL(SUM(`PenyesuaianStok`),0) AS 'Stok' FROM `tbpenyesuaianstok` WHERE `IdBarang`=(SELECT `IdBarang` FROM `tbmbarang` AS A JOIN `tbmkategoribarang` AS B ON A.`IdKategoriBarang`=B.`IdKategoriBarang` JOIN `tbmjenisbarang` AS C ON B.`IdJenisBarang`=C.`IdJenisBarang` WHERE `JenisBarang`='" + JTJenisBarang.getText() + "' AND `KategoriBarang`='" + JTKategoriBarang.getText() + "' AND `NamaBarang`='" + JTNamaBarang.getText() + "')) AS `stok`");
            ArrayList<String> list = dRunSelctOne.excute();
            String Stok = list.get(0);
            if (!idEdit.equals("0") && JTJenisBarang.getText().equals(jenisBarang) && JTKategoriBarang.getText().equals(kategoriBarang) && JTNamaBarang.getText().equals(namaBarang)) {
                Stok = String.valueOf(Integer.parseInt(Stok) + Integer.parseInt(jumlahBarangKeluar));
            }
            JRStokBarang.setText(Stok);
        }
    }

    void loadSerialNumber(String query) {
        if (!JTJenisBarang.getText().isEmpty() && !JTKategoriBarang.getText().isEmpty() && !JTNamaBarang.getText().isEmpty()) {
            RunSelct runSelct = new RunSelct();
            runSelct.setQuery("SELECT A.`IdDetailBarangMasuk`, `SerialNumber` FROM `tbbarangmasukdetail` AS A JOIN `tbmbarang` AS B ON A.`IdBarang`=B.`IdBarang` JOIN `tbmkategoribarang` AS C ON B.`IdKategoriBarang`=C.`IdKategoriBarang` JOIN `tbmjenisbarang` AS D ON C.`IdJenisBarang`=D.`IdJenisBarang` LEFT JOIN `tbbarangkeluar` AS E ON A.`IdDetailBarangMasuk`=E.`IdDetailBarangMasuk` WHERE `JenisBarang`='" + JTJenisBarang.getText() + "' AND `KategoriBarang`='" + JTKategoriBarang.getText() + "' AND `NamaBarang`='" + JTNamaBarang.getText() + "' AND (`IdBarangKeluar` IS NULL" + query + ")");
            try {
                ResultSet rs = runSelct.excute();
                int row = 0;
                if (rs.last()) {
                    idDetailBarangMasuk = new String[rs.getRow()];
                    rs.beforeFirst();
                }
                DefaultComboBoxModel modelbaru = new DefaultComboBoxModel();
                JCSerialNumber.setModel(modelbaru);
                JCSerialNumber.addItem("-- Pilih Serial Number --");
                while (rs.next()) {
                    idDetailBarangMasuk[row] = rs.getString(1);
                    JCSerialNumber.addItem(rs.getString(2));
                    row++;
                }

            } catch (SQLException e) {
                out.println("E6" + e);
                JOptionPane.showMessageDialog(this, "Gagal Load Serial Number", "Information", JOptionPane.INFORMATION_MESSAGE);
            } finally {
                runSelct.closecon();
            }
        }
    }

    boolean checkInput() {
        if (JTNomorBarangKeluar.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Nomor Barang Keluar Tidak Boleh Kosong", "Information", JOptionPane.INFORMATION_MESSAGE);
            return false;
        } else if (JDTanggalBarangKeluar.getDate() == null) {
            JOptionPane.showMessageDialog(this, "Tanggal Barang Keluar Tidak Boleh Kosong", "Information", JOptionPane.INFORMATION_MESSAGE);
            JDTanggalBarangKeluar.requestFocus();
            return false;
        } else if (JCNamaPemakai.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(this, "Nama Pemakai Harus Dipilih", "Information", JOptionPane.INFORMATION_MESSAGE);
            JCNamaPemakai.requestFocus();
            return false;
        } else if (JTJenisBarang.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Jenis Barang Tidak Boleh Kosong", "Information", JOptionPane.INFORMATION_MESSAGE);
            JTCariBarang.requestFocus();
            return false;
        } else if (JTKategoriBarang.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Kategori Barang Tidak Boleh Kosong", "Information", JOptionPane.INFORMATION_MESSAGE);
            JTCariBarang.requestFocus();
            return false;
        } else if (JTNamaBarang.getText().replace(" ", "").isEmpty()) {
            JOptionPane.showMessageDialog(this, "Nama Barang Tidak Boleh Kosong", "Information", JOptionPane.INFORMATION_MESSAGE);
            JTCariBarang.requestFocus();
            return false;
        } else if (JRStokBarang.getInt() < JRJumlahBarangKeluar.getInt()) {
            JOptionPane.showMessageDialog(this, "Stok Barang Tidak Mencukupi", "Information", JOptionPane.INFORMATION_MESSAGE);
            JRJumlahBarangKeluar.requestFocus();
            return false;
        } else if (JRJumlahBarangKeluar.getInt() < 1) {
            JOptionPane.showMessageDialog(this, "Jumlah Barang Keluar Minimal 1", "Information", JOptionPane.INFORMATION_MESSAGE);
            JRJumlahBarangKeluar.requestFocus();
            return false;
        } else if (JCSerialNumber.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(this, "Serial Number Harus Dipilih", "Information", JOptionPane.INFORMATION_MESSAGE);
            JCSerialNumber.requestFocus();
            return false;
        } else {
            return true;
        }
    }

    void tambah(boolean tutup) {
        if (checkInput()) {
            Insert insert = new LSubProces.Insert();
            boolean simpan = insert.Simpan("INSERT INTO `tbbarangkeluar`(`NomorBarangKeluar`, `TanggalBarangKeluar`, `IdKaryawan`, `IdBarang`, `JumlahBarang`, `IdDetailBarangMasuk`, `Keterangan`) VALUES ('" + JTNomorBarangKeluar.getText() + "', '" + FDateF.datetostr(JDTanggalBarangKeluar.getDate(), "yyyy-MM-dd") + "', (SELECT `IdKaryawan` FROM `tbmkaryawan` WHERE `NamaKaryawan`='" + JCNamaPemakai.getSelectedItem() + "'), (SELECT `IdBarang` FROM `tbmbarang` AS A JOIN `tbmkategoribarang` AS B ON A.`IdKategoriBarang`=B.`IdKategoriBarang` JOIN `tbmjenisbarang` AS C ON B.`IdJenisBarang`=C.`IdJenisBarang` WHERE `JenisBarang`='" + JTJenisBarang.getText() + "' AND `KategoriBarang`='" + JTKategoriBarang.getText() + "' AND `NamaBarang`='" + JTNamaBarang.getText() + "'), '" + JRJumlahBarangKeluar.getInt() + "', '" + idDetailBarangMasuk[JCSerialNumber.getSelectedIndex() - 1] + "', '" + JTKeterangan.getText() + "')", "Tambah Data Barang Keluar", this);
            if (simpan) {
                if (GlobalVar.Var.listBarangKeluar != null) {
                    GlobalVar.Var.listBarangKeluar.load();
                }
                if (tutup) {
                    GlobalVar.Var.tambahBarangKeluar.dispose();
                } else {
                    clearText();
                    setNomorBarangKeluar();
                    JCNamaPemakai.requestFocus();
                }
            }
        }
    }

    void clearText() {
        JDTanggalBarangKeluar.setDate(new Date());
        JCNamaPemakai.setSelectedIndex(0);
        JTJenisBarang.setText("");
        JTKategoriBarang.setText("");
        JTNamaBarang.setText("");
        JTCariBarang.setText("");
        JRStokBarang.setText("0");
        JRJumlahBarangKeluar.setText("1");
        JCSerialNumber.setSelectedIndex(0);
        JTKeterangan.setText("");
    }

    void loadData() {
        DRunSelctOne dRunSelctOne = new DRunSelctOne();
        dRunSelctOne.seterorm("Gagal Menampilkan Data Barang Keluar");
        dRunSelctOne.setQuery("SELECT `IdBarangKeluar`, `NomorBarangKeluar`, `TanggalBarangKeluar`, `NamaKaryawan`, `JenisBarang`, `KategoriBarang`, `NamaBarang`, A.`JumlahBarang`, `IdDetailBarangMasuk`, A.`Keterangan` FROM `tbbarangkeluar` AS A JOIN `tbmkaryawan` AS B ON A.`IdKaryawan`=B.`IdKaryawan` JOIN `tbmbarang` AS C ON A.`IdBarang`=C.`IdBarang` JOIN `tbmkategoribarang` AS D ON C.`IdKategoriBarang`=D.`IdKategoriBarang` JOIN `tbmjenisbarang` AS E ON D.`IdJenisBarang`=E.`IdJenisBarang` WHERE `IdBarangKeluar`='" + idEdit + "'");
        ArrayList<String> list = dRunSelctOne.excute();
        JTNomorBarangKeluar.setText(list.get(1));
        JDTanggalBarangKeluar.setDate(FDateF.strtodate(list.get(2), "yyyy-MM-dd"));
        JCNamaPemakai.setSelectedItem(list.get(3));
        JTJenisBarang.setText(list.get(4));
        JTKategoriBarang.setText(list.get(5));
        JTNamaBarang.setText(list.get(6));
        jenisBarang = list.get(4);
        kategoriBarang = list.get(5);
        namaBarang = list.get(6);
        jumlahBarangKeluar = list.get(7);
        setStokBarang();
        JRJumlahBarangKeluar.setText(list.get(7));
        loadSerialNumber(" OR `IdBarangKeluar`=" + list.get(0));
        JCSerialNumber.setSelectedIndex(getIndexSerialNumber(list.get(8)));
        JTKeterangan.setText(list.get(9));
    }

    int getIndexSerialNumber(String id) {
        for (int i = 0; i < idDetailBarangMasuk.length; i++) {
            if (idDetailBarangMasuk[i].equals(id)) {
                return (i + 1);
            }
        }
        return 0;
    }

    void ubah() {
        if (checkInput()) {
            Update update = new LSubProces.Update();
            boolean ubah = update.Ubah("UPDATE `tbbarangkeluar` SET `TanggalBarangKeluar`='" + FDateF.datetostr(JDTanggalBarangKeluar.getDate(), "yyyy-MM-dd") + "', `IdKaryawan`=(SELECT `IdKaryawan` FROM `tbmkaryawan` WHERE `NamaKaryawan`='" + JCNamaPemakai.getSelectedItem() + "'), `IdBarang`=(SELECT `IdBarang` FROM `tbmbarang` AS A JOIN `tbmkategoribarang` AS B ON A.`IdKategoriBarang`=B.`IdKategoriBarang` JOIN `tbmjenisbarang` AS C ON B.`IdJenisBarang`=C.`IdJenisBarang` WHERE `JenisBarang`='" + JTJenisBarang.getText() + "' AND `KategoriBarang`='" + JTKategoriBarang.getText() + "' AND `NamaBarang`='" + JTNamaBarang.getText() + "'), `JumlahBarang`='" + JRJumlahBarangKeluar.getInt() + "', `IdDetailBarangMasuk`='" + idDetailBarangMasuk[JCSerialNumber.getSelectedIndex() - 1] + "', `Keterangan`='" + JTKeterangan.getText() + "' WHERE `IdBarangKeluar`=" + idEdit, "Ubah Data Barang Keluar", this);
            if (ubah) {
                dispose();
                if (GlobalVar.Var.listBarangKeluar != null) {
                    GlobalVar.Var.listBarangKeluar.load();
                }
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private KomponenGUI.JbuttonF JBCariBarang;
    private KomponenGUI.JbuttonF JBKembali;
    private KomponenGUI.JbuttonF JBNamaPemakai;
    private KomponenGUI.JbuttonF JBTambah;
    private KomponenGUI.JbuttonF JBTambahTutup;
    private KomponenGUI.JbuttonF JBUbah;
    public KomponenGUI.JcomboboxF JCNamaPemakai;
    private KomponenGUI.JcomboboxF JCSerialNumber;
    private KomponenGUI.JdateCF JDTanggalBarangKeluar;
    private KomponenGUI.JlableF JLCariBarang;
    private KomponenGUI.JlableF JLCariBarang2;
    private KomponenGUI.JlableF JLJenisBarang;
    private KomponenGUI.JlableF JLJenisBarang2;
    private KomponenGUI.JlableF JLJumlahBarangKeluar;
    private KomponenGUI.JlableF JLJumlahBarangKeluar2;
    private KomponenGUI.JlableF JLKategoriBarang;
    private KomponenGUI.JlableF JLKategoriBarang2;
    private KomponenGUI.JlableF JLKeterangan;
    private KomponenGUI.JlableF JLKeterangan2;
    private KomponenGUI.JlableF JLNamaBarang;
    private KomponenGUI.JlableF JLNamaBarang2;
    private KomponenGUI.JlableF JLNamaPemakai;
    private KomponenGUI.JlableF JLNamaPemakai2;
    private KomponenGUI.JlableF JLNomoBarangKeluar2;
    private KomponenGUI.JlableF JLNomorBarangKeluar;
    private KomponenGUI.JlableF JLSerialNumber;
    private KomponenGUI.JlableF JLSerialNumber2;
    private KomponenGUI.JlableF JLStokBarang;
    private KomponenGUI.JlableF JLStokBarang2;
    private KomponenGUI.JlableF JLTanggalBarangKeluar;
    private KomponenGUI.JlableF JLTanggalBarangKeluar2;
    private KomponenGUI.JRibuanTextField JRJumlahBarangKeluar;
    private KomponenGUI.JRibuanTextField JRStokBarang;
    private javax.swing.JScrollPane JSPKeterangan;
    private KomponenGUI.JtextF JTCariBarang;
    private KomponenGUI.JtextF JTJenisBarang;
    private KomponenGUI.JtextF JTKategoriBarang;
    private KomponenGUI.JTextAreaF JTKeterangan;
    private KomponenGUI.JtextF JTNamaBarang;
    private KomponenGUI.JtextF JTNomorBarangKeluar;
    // End of variables declaration//GEN-END:variables
}
