/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Laporan;

import KomponenGUI.FDateF;
import LSubProces.FLaporan;
import LSubProces.History;
import java.awt.event.KeyEvent;
import java.util.Date;
import java.util.HashMap;
import java.util.Locale;
import net.sf.jasperreports.engine.JRParameter;

/**
 *
 * @author Martono
 */
public class LaporanMasterBarang extends javax.swing.JFrame {

    /**
     * Creates new form LaporanMasterVendor
     */
    public LaporanMasterBarang() {
        initComponents();
        setLocationRelativeTo(null);
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        setTitle("Laporan Master Barang");
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BGGaransi = new javax.swing.ButtonGroup();
        JLLaporanMasterBarang = new KomponenGUI.JlableF();
        JLJenisBarang = new KomponenGUI.JlableF();
        JLJenisBarang2 = new KomponenGUI.JlableF();
        JCJenisBarang = new KomponenGUI.JcomboboxF();
        JLKategoriBarang = new KomponenGUI.JlableF();
        JLKategoriBarang2 = new KomponenGUI.JlableF();
        JCKategoriBarang = new KomponenGUI.JcomboboxF();
        JLGaransi = new KomponenGUI.JlableF();
        JLGaransi2 = new KomponenGUI.JlableF();
        JRBGaransiSemua = new KomponenGUI.JRadioButtonF();
        JRBGaransiYa = new KomponenGUI.JRadioButtonF();
        JRBGaransiTidak = new KomponenGUI.JRadioButtonF();
        JBTampilkan = new KomponenGUI.JbuttonF();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        JLLaporanMasterBarang.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLLaporanMasterBarang.setText("LAPORAN MASTER BARANG");

        JLJenisBarang.setText("Jenis Barang");

        JLJenisBarang2.setText(":");

        JCJenisBarang.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-- Semua Jenis Barang --" }));
        JCJenisBarang.load("SELECT '-- Semua Jenis Barang --' AS `JenisBarang` UNION SELECT `JenisBarang` FROM `tbmjenisbarang`");
        JCJenisBarang.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                JCJenisBarangItemStateChanged(evt);
            }
        });
        JCJenisBarang.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                JCJenisBarangKeyReleased(evt);
            }
        });

        JLKategoriBarang.setText("Kategori Barang");

        JLKategoriBarang2.setText(":");

        JCKategoriBarang.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-- Semua Kategori Barang --" }));
        JCKategoriBarang.load("SELECT '-- Semua Kategori Barang --' AS `KategoriBarang` UNION SELECT `KategoriBarang` FROM `tbmkategoribarang`");
        JCKategoriBarang.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                JCKategoriBarangKeyReleased(evt);
            }
        });

        JLGaransi.setText("Garansi");

        JLGaransi2.setText(":");

        BGGaransi.add(JRBGaransiSemua);
        JRBGaransiSemua.setSelected(true);
        JRBGaransiSemua.setText("Semua");
        JRBGaransiSemua.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                JRBGaransiSemuaKeyReleased(evt);
            }
        });

        BGGaransi.add(JRBGaransiYa);
        JRBGaransiYa.setText("Ya");
        JRBGaransiYa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                JRBGaransiYaKeyReleased(evt);
            }
        });

        BGGaransi.add(JRBGaransiTidak);
        JRBGaransiTidak.setText("Tidak");
        JRBGaransiTidak.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                JRBGaransiTidakKeyReleased(evt);
            }
        });

        JBTampilkan.setText("Tampilkan");
        JBTampilkan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBTampilkanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(JBTampilkan, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(JLKategoriBarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(JLKategoriBarang2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(JCKategoriBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(JLGaransi, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(JLGaransi2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(13, 13, 13)
                                    .addComponent(JRBGaransiSemua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(JRBGaransiYa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(JRBGaransiTidak, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(JLJenisBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(JLJenisBarang2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(JCJenisBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(JLLaporanMasterBarang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JLLaporanMasterBarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JLJenisBarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JLJenisBarang2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JCJenisBarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JLKategoriBarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JLKategoriBarang2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JCKategoriBarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JLGaransi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JLGaransi2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JRBGaransiSemua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JRBGaransiYa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JRBGaransiTidak, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(JBTampilkan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JBTampilkanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBTampilkanActionPerformed
        tampilkan();
    }//GEN-LAST:event_JBTampilkanActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        GlobalVar.Var.laporanMasterBarang = null;
    }//GEN-LAST:event_formWindowClosed

    private void JCJenisBarangKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JCJenisBarangKeyReleased
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            JCKategoriBarang.requestFocus();
        }
    }//GEN-LAST:event_JCJenisBarangKeyReleased

    private void JCKategoriBarangKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JCKategoriBarangKeyReleased
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (JRBGaransiSemua.isSelected()) {
                JRBGaransiSemua.requestFocus();
            } else if (JRBGaransiYa.isSelected()) {
                JRBGaransiYa.requestFocus();
            } else {
                JRBGaransiTidak.requestFocus();
            }
        }
    }//GEN-LAST:event_JCKategoriBarangKeyReleased

    private void JRBGaransiSemuaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JRBGaransiSemuaKeyReleased
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            tampilkan();
        }
    }//GEN-LAST:event_JRBGaransiSemuaKeyReleased

    private void JRBGaransiYaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JRBGaransiYaKeyReleased
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            tampilkan();
        }
    }//GEN-LAST:event_JRBGaransiYaKeyReleased

    private void JRBGaransiTidakKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JRBGaransiTidakKeyReleased
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            tampilkan();
        }
    }//GEN-LAST:event_JRBGaransiTidakKeyReleased

    private void JCJenisBarangItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_JCJenisBarangItemStateChanged
        if (JCJenisBarang.getSelectedIndex() == 0) {
            JCKategoriBarang.load("SELECT '-- Semua Kategori Barang --' AS `KategoriBarang` UNION SELECT `KategoriBarang` FROM `tbmkategoribarang`");
        } else {
            JCKategoriBarang.load("SELECT '-- Semua Kategori Barang --' AS `KategoriBarang` UNION SELECT `KategoriBarang` FROM `tbmkategoribarang` AS A JOIN `tbmjenisbarang` AS B ON A.`IdJenisBarang`=B.`IdJenisBarang` WHERE `JenisBarang`='" + JCJenisBarang.getSelectedItem() + "'");
        }
    }//GEN-LAST:event_JCJenisBarangItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LaporanMasterBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LaporanMasterBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LaporanMasterBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LaporanMasterBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LaporanMasterBarang();
            }
        });
    }

    void tampilkan() {
        String jenisBarang, kategoriBarang, garansi;
        HashMap hashs = new HashMap();
        java.util.Locale locale = new Locale("id", "ID");
        hashs.put(JRParameter.REPORT_LOCALE, locale);
        FLaporan fLaporan = new FLaporan();
        hashs.put("Title", "Laporan Master Barang");
        if (JCJenisBarang.getSelectedIndex() == 0) {
            jenisBarang = "";
            hashs.put("JenisBarang", "Semua Jenis");
        } else {
            jenisBarang = " AND `JenisBarang`='" + JCJenisBarang.getSelectedItem() + "'";
            hashs.put("JenisBarang", JCJenisBarang.getSelectedItem());
        }
        if (JCKategoriBarang.getSelectedIndex() == 0) {
            kategoriBarang = "";
            hashs.put("KategoriBarang", "Semua Kategori");
        } else {
            kategoriBarang = " AND `KategoriBarang`='" + JCKategoriBarang.getSelectedItem() + "'";
            hashs.put("KategoriBarang", JCKategoriBarang.getSelectedItem());
        }
        if (JRBGaransiSemua.isSelected()) {
            garansi = "";
            hashs.put("Garansi", "Semua");
        } else if (JRBGaransiYa.isSelected()) {
            garansi = " AND `Garansi`='Ya'";
            hashs.put("Garansi", "Ya");
        } else {
            garansi = " AND `Garansi`='Tidak'";
            hashs.put("Garansi", "Tidak");
        }
        hashs.put("PrintedBy", "Di Print Oleh " + GlobalVar.VarL.username + " Pada " + FDateF.datetostr(new Date(), "dd/MM/yyyy HH:mm"));
        hashs.put("Where", jenisBarang + kategoriBarang + garansi);
        fLaporan.sethashmap(hashs);
        fLaporan.setfilename("LaporanMasterBarang");
        fLaporan.setErorm("Gagal Menampilkan " + this.getTitle());
        fLaporan.excute();
        History.simpanhistory(GlobalVar.VarL.username, "Melihat Laporan Master Barang");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup BGGaransi;
    private KomponenGUI.JbuttonF JBTampilkan;
    private KomponenGUI.JcomboboxF JCJenisBarang;
    private KomponenGUI.JcomboboxF JCKategoriBarang;
    private KomponenGUI.JlableF JLGaransi;
    private KomponenGUI.JlableF JLGaransi2;
    private KomponenGUI.JlableF JLJenisBarang;
    private KomponenGUI.JlableF JLJenisBarang2;
    private KomponenGUI.JlableF JLKategoriBarang;
    private KomponenGUI.JlableF JLKategoriBarang2;
    private KomponenGUI.JlableF JLLaporanMasterBarang;
    private KomponenGUI.JRadioButtonF JRBGaransiSemua;
    private KomponenGUI.JRadioButtonF JRBGaransiTidak;
    private KomponenGUI.JRadioButtonF JRBGaransiYa;
    // End of variables declaration//GEN-END:variables
}
