package Master;

import LSubProces.DRunSelctOne;
import LSubProces.Insert;
import LSubProces.Update;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import java.awt.event.KeyEvent;

/**
 *
 * @author Martono
 */
public class MasterBarang extends javax.swing.JFrame {

    String idEdit;
    String[] data;

    /**
     * Creates new form MasterPemasok
     */
    public MasterBarang(Object id) {
        initComponents();
        setLocationRelativeTo(null);
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        idEdit = id.toString();
        data = idEdit.split("\\+");
        if (idEdit.equals("0") || data.length > 1) {
            setTitle("Tambah Master Barang");
            if (data.length > 1) {
                JCJenisBarang.setSelectedItem(data[1]);
                JCKategoriBarang.setSelectedItem(data[2]);
                JTNamaBarang.requestFocus();
            }
            JBUbah.setVisible(false);
        } else {
            setTitle("Ubah Master Barang");
            loadData();
            JBTambah.setVisible(false);
            JBTambahTutup.setVisible(false);
        }
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BGGaransi = new javax.swing.ButtonGroup();
        JLJenisBarang = new KomponenGUI.JlableF();
        JLJenisBarang2 = new KomponenGUI.JlableF();
        JCJenisBarang = new KomponenGUI.JcomboboxF();
        JBJenisBarang = new KomponenGUI.JbuttonF();
        JLKategoriBarang = new KomponenGUI.JlableF();
        JLKategoriBarang2 = new KomponenGUI.JlableF();
        JCKategoriBarang = new KomponenGUI.JcomboboxF();
        JBKategoriBarang = new KomponenGUI.JbuttonF();
        JLNamaBarang = new KomponenGUI.JlableF();
        JLNamaBarang2 = new KomponenGUI.JlableF();
        JTNamaBarang = new KomponenGUI.JtextF();
        JLGaransi = new KomponenGUI.JlableF();
        JLGaransi2 = new KomponenGUI.JlableF();
        JRBGaransiYa = new KomponenGUI.JRadioButtonF();
        JRBGaransiTidak = new KomponenGUI.JRadioButtonF();
        JLSatuan = new KomponenGUI.JlableF();
        JLSatuan2 = new KomponenGUI.JlableF();
        JTSatuan = new KomponenGUI.JtextF();
        JLKeterangan = new KomponenGUI.JlableF();
        JLKeterangan2 = new KomponenGUI.JlableF();
        JSPKeterangan = new javax.swing.JScrollPane();
        JTKeterangan = new KomponenGUI.JTextAreaF();
        JBKembali = new KomponenGUI.JbuttonF();
        JBTambah = new KomponenGUI.JbuttonF();
        JBTambahTutup = new KomponenGUI.JbuttonF();
        JBUbah = new KomponenGUI.JbuttonF();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        JLJenisBarang.setText("Jenis Barang");

        JLJenisBarang2.setText(":");

        JCJenisBarang.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-- Pilih Jenis Barang --" }));
        JCJenisBarang.load("SELECT '-- Pilih Jenis Barang --' AS `JenisBarang` UNION SELECT `JenisBarang` FROM `tbmjenisbarang`");
        JCJenisBarang.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                JCJenisBarangItemStateChanged(evt);
            }
        });
        JCJenisBarang.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                JCJenisBarangKeyReleased(evt);
            }
        });

        JBJenisBarang.setText("+");
        JBJenisBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBJenisBarangActionPerformed(evt);
            }
        });

        JLKategoriBarang.setText("Kategori Barang");

        JLKategoriBarang2.setText(":");

        JCKategoriBarang.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-- Pilih Kategori Barang --" }));
        JCKategoriBarang.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                JCKategoriBarangKeyReleased(evt);
            }
        });

        JBKategoriBarang.setText("+");
        JBKategoriBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBKategoriBarangActionPerformed(evt);
            }
        });

        JLNamaBarang.setText("Nama Barang");

        JLNamaBarang2.setText(":");

        JTNamaBarang.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                JTNamaBarangKeyReleased(evt);
            }
        });
        JTNamaBarang.setMaxText(50);

        JLGaransi.setText("Garansi");

        JLGaransi2.setText(":");

        BGGaransi.add(JRBGaransiYa);
        JRBGaransiYa.setText("Ya");
        JRBGaransiYa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                JRBGaransiYaKeyReleased(evt);
            }
        });

        BGGaransi.add(JRBGaransiTidak);
        JRBGaransiTidak.setText("Tidak");
        JRBGaransiTidak.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                JRBGaransiTidakKeyReleased(evt);
            }
        });

        JLSatuan.setText("Satuan");

        JLSatuan2.setText(":");

        JTSatuan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                JTSatuanKeyReleased(evt);
            }
        });
        JTSatuan.setMaxText(25);

        JLKeterangan.setText("Keterangan");

        JLKeterangan2.setText(":");

        JTKeterangan.setColumns(20);
        JTKeterangan.setLineWrap(true);
        JTKeterangan.setRows(5);
        JTKeterangan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                JTKeteranganKeyPressed(evt);
            }
        });
        JSPKeterangan.setViewportView(JTKeterangan);

        JBKembali.setText("Kembali");
        JBKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBKembaliActionPerformed(evt);
            }
        });

        JBTambah.setText("Tambah");
        JBTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBTambahActionPerformed(evt);
            }
        });

        JBTambahTutup.setText("Tambah dan Tutup");
        JBTambahTutup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBTambahTutupActionPerformed(evt);
            }
        });

        JBUbah.setText("Ubah");
        JBUbah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBUbahActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(JBKembali, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(JBTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(JBTambahTutup, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(JBUbah, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(JLKategoriBarang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(JLJenisBarang, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(JLKeterangan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(6, 6, 6)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(JLJenisBarang2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(JCJenisBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(JBJenisBarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(JLKategoriBarang2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(JLKeterangan2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(JLGaransi2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(16, 16, 16)
                                                .addComponent(JRBGaransiYa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(JRBGaransiTidak, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(0, 0, Short.MAX_VALUE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(JSPKeterangan)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(JCKategoriBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(JBKategoriBarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(0, 0, Short.MAX_VALUE))))))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(JLNamaBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(JLNamaBarang2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(JTNamaBarang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(10, 10, 10))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(JLSatuan, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(JLGaransi, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JLSatuan2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JTSatuan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JLJenisBarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JLJenisBarang2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JCJenisBarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JBJenisBarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JLKategoriBarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JLKategoriBarang2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JCKategoriBarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JBKategoriBarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JLNamaBarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JTNamaBarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JLNamaBarang2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JLGaransi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JRBGaransiYa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JRBGaransiTidak, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JLGaransi2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JLSatuan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JLSatuan2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JTSatuan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JLKeterangan2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JLKeterangan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(JSPKeterangan, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JBTambahTutup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JBTambah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JBUbah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JBKembali, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JBTambahTutupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBTambahTutupActionPerformed
        tambah(true);
    }//GEN-LAST:event_JBTambahTutupActionPerformed

    private void JBTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBTambahActionPerformed
        tambah(false);
    }//GEN-LAST:event_JBTambahActionPerformed

    private void JBKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBKembaliActionPerformed
        if (idEdit.equals("0") || data.length > 1) {
            GlobalVar.Var.tambahMasterBarang.dispose();
        } else {
            GlobalVar.Var.editMasterBarang.dispose();
        }
    }//GEN-LAST:event_JBKembaliActionPerformed

    private void JBUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBUbahActionPerformed
        ubah();
    }//GEN-LAST:event_JBUbahActionPerformed

    private void JTNamaBarangKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JTNamaBarangKeyReleased
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (JRBGaransiTidak.isSelected()) {
                JRBGaransiTidak.requestFocus();
            } else {
                JRBGaransiYa.requestFocus();
            }
        }
    }//GEN-LAST:event_JTNamaBarangKeyReleased

    private void JTKeteranganKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JTKeteranganKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (JBTambah.isVisible()) {
                tambah(false);
            } else {
                ubah();
            }
        }
    }//GEN-LAST:event_JTKeteranganKeyPressed

    private void JBJenisBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBJenisBarangActionPerformed
        if (GlobalVar.Var.tambahMasterJenisBarang == null) {
            GlobalVar.Var.tambahMasterJenisBarang = new MasterJenisBarang("0");
        } else {
            GlobalVar.Var.tambahMasterJenisBarang.setState(NORMAL);
            GlobalVar.Var.tambahMasterJenisBarang.toFront();
        }
    }//GEN-LAST:event_JBJenisBarangActionPerformed

    private void JCJenisBarangKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JCJenisBarangKeyReleased
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (JCJenisBarang.getSelectedIndex() == 0) {
                JCJenisBarang.showPopup();
            } else {
                JCKategoriBarang.requestFocus();
            }
        }
    }//GEN-LAST:event_JCJenisBarangKeyReleased

    private void JCKategoriBarangKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JCKategoriBarangKeyReleased
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (JCKategoriBarang.getSelectedIndex() == 0) {
                JCKategoriBarang.showPopup();
            } else {
                JTNamaBarang.requestFocus();
            }
        }
    }//GEN-LAST:event_JCKategoriBarangKeyReleased

    private void JBKategoriBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBKategoriBarangActionPerformed
        if (GlobalVar.Var.tambahMasterKategoriBarang == null) {
            GlobalVar.Var.tambahMasterKategoriBarang = new MasterKategoriBarang("0+" + JCJenisBarang.getSelectedItem());
        } else {
            GlobalVar.Var.tambahMasterKategoriBarang.setState(NORMAL);
            GlobalVar.Var.tambahMasterKategoriBarang.toFront();
        }
    }//GEN-LAST:event_JBKategoriBarangActionPerformed

    private void JCJenisBarangItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_JCJenisBarangItemStateChanged
        JCKategoriBarang.load("SELECT '-- Pilih Kategori Barang --' AS `KategoriBarang` UNION SELECT `KategoriBarang` FROM `tbmkategoribarang` AS A JOIN `tbmjenisbarang` AS B ON A.`IdJenisBarang`=B.`IdJenisBarang` WHERE `JenisBarang`='" + JCJenisBarang.getSelectedItem() + "'");
    }//GEN-LAST:event_JCJenisBarangItemStateChanged

    private void JRBGaransiYaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JRBGaransiYaKeyReleased
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            JRBGaransiYa.setSelected(true);
            JTSatuan.requestFocus();
        }
    }//GEN-LAST:event_JRBGaransiYaKeyReleased

    private void JRBGaransiTidakKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JRBGaransiTidakKeyReleased
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            JRBGaransiTidak.setSelected(true);
            JTSatuan.requestFocus();
        }
    }//GEN-LAST:event_JRBGaransiTidakKeyReleased

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        if (idEdit.equals("0") || data.length > 1) {
            GlobalVar.Var.tambahMasterBarang = null;
        } else {
            GlobalVar.Var.editMasterBarang = null;
        }
    }//GEN-LAST:event_formWindowClosed

    private void JTSatuanKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JTSatuanKeyReleased
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            JTKeterangan.requestFocus();
        }
    }//GEN-LAST:event_JTSatuanKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MasterBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MasterBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MasterBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MasterBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MasterBarang("0");
            }
        });
    }

    boolean checkInput() {
        if (JCJenisBarang.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(this, "Jenis Barang Harus Dipilih", "Information", JOptionPane.INFORMATION_MESSAGE);
            JCJenisBarang.requestFocus();
            return false;
        } else if (JCKategoriBarang.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(this, "Kategori Barang Harus Dipilih", "Information", JOptionPane.INFORMATION_MESSAGE);
            JCKategoriBarang.requestFocus();
            return false;
        } else if (JTNamaBarang.getText().replace(" ", "").isEmpty()) {
            JOptionPane.showMessageDialog(this, "Nama Barang Tidak Boleh Kosong", "Information", JOptionPane.INFORMATION_MESSAGE);
            JTNamaBarang.requestFocus();
            return false;
        } else if (!JRBGaransiYa.isSelected() && !JRBGaransiTidak.isSelected()) {
            JOptionPane.showMessageDialog(this, "Garansi Harus Dipilih", "Information", JOptionPane.INFORMATION_MESSAGE);
            JRBGaransiYa.requestFocus();
            return false;
        } else if (JTSatuan.getText().replace(" ", "").isEmpty()) {
            JOptionPane.showMessageDialog(this, "Satuan Tidak Boleh Kosong", "Information", JOptionPane.INFORMATION_MESSAGE);
            JTSatuan.requestFocus();
            return false;
        } else {
            return true;
        }
    }

    void tambah(boolean tutup) {
        if (checkInput()) {
            String garansi;
            if (JRBGaransiYa.isSelected()) {
                garansi = "Ya";
            } else {
                garansi = "Tidak";
            }
            Insert insert = new LSubProces.Insert();
            boolean simpan = insert.Simpan("INSERT INTO `tbmbarang`(`IdKategoriBarang`, `NamaBarang`, `Garansi`, `Satuan`, `Keterangan`) VALUES ((SELECT `IdKategoriBarang` FROM `tbmkategoribarang` AS A JOIN `tbmjenisbarang` AS B ON A.`IdJenisBarang`=B.`IdJenisBarang` WHERE `JenisBarang`='" + JCJenisBarang.getSelectedItem() + "' AND `KategoriBarang`='" + JCKategoriBarang.getSelectedItem() + "'), '" + JTNamaBarang.getText() + "', '" + garansi + "', '" + JTSatuan.getText() + "', '" + JTKeterangan.getText() + "')", "Tambah Data Master Barang", this);
            if (simpan) {
                if (GlobalVar.Var.listMasterBarang != null) {
                    GlobalVar.Var.listMasterBarang.load();
                }
                if (GlobalVar.Var.tambahBarangRusak != null) {
                    GlobalVar.Var.tambahBarangRusak.JCNamaBarang.load("SELECT '-- Pilih Nama Barang --' AS `NamaBarang` UNION SELECT `NamaBarang` FROM `tbmbarang` AS A JOIN `tbmkategoribarang` AS B ON A.`IdKategoriBarang`=B.`IdKategoriBarang` JOIN `tbmjenisbarang` AS C ON B.`IdJenisBarang`=C.`IdJenisBarang` WHERE `JenisBarang`='" + JCJenisBarang.getSelectedItem() + "' AND `KategoriBarang`='" + JCKategoriBarang.getSelectedItem() + "'");
                    GlobalVar.Var.tambahBarangRusak.JCNamaBarang.setSelectedItem(JTNamaBarang.getText());
                    GlobalVar.Var.tambahBarangRusak.JCNamaBarang.requestFocus();
                }
                if (GlobalVar.Var.editBarangRusak != null) {
                    GlobalVar.Var.editBarangRusak.JCNamaBarang.load("SELECT '-- Pilih Nama Barang --' AS `NamaBarang` UNION SELECT `NamaBarang` FROM `tbmbarang` AS A JOIN `tbmkategoribarang` AS B ON A.`IdKategoriBarang`=B.`IdKategoriBarang` JOIN `tbmjenisbarang` AS C ON B.`IdJenisBarang`=C.`IdJenisBarang` WHERE `JenisBarang`='" + JCJenisBarang.getSelectedItem() + "' AND `KategoriBarang`='" + JCKategoriBarang.getSelectedItem() + "'");
                    GlobalVar.Var.editBarangRusak.JCNamaBarang.setSelectedItem(JTNamaBarang.getText());
                    GlobalVar.Var.editBarangRusak.JCNamaBarang.requestFocus();
                }
                if (tutup) {
                    GlobalVar.Var.tambahMasterBarang.dispose();
                } else {
                    clearText();
                    JCJenisBarang.requestFocus();
                }
            }
        }
    }

    void clearText() {
        JTNamaBarang.setText("");
        JTSatuan.setText("");
        JTKeterangan.setText("");
    }

    void loadData() {
        DRunSelctOne dRunSelctOne = new DRunSelctOne();
        dRunSelctOne.seterorm("Gagal Menampilkan Data Master Barang");
        dRunSelctOne.setQuery("SELECT `IdBarang`, `JenisBarang`, `KategoriBarang`, `NamaBarang`, `Garansi`, `Satuan`, A.`Keterangan` FROM `tbmbarang` AS A JOIN `tbmkategoribarang` AS B ON A.`IdKategoriBarang`=B.`IdKategoriBarang` JOIN `tbmjenisbarang` AS C ON B.`IdJenisBarang`=C.`IdJenisBarang` WHERE `IdBarang`='" + idEdit + "'");
        ArrayList<String> list = dRunSelctOne.excute();
        JCJenisBarang.setSelectedItem(list.get(1));
        JCKategoriBarang.setSelectedItem(list.get(2));
        JTNamaBarang.setText(list.get(3));
        if (list.get(4).equals("Ya")) {
            JRBGaransiYa.setSelected(true);
        } else {
            JRBGaransiTidak.setSelected(true);
        }
        JTSatuan.setText(list.get(5));
        JTKeterangan.setText(list.get(6));
    }

    void ubah() {
        if (checkInput()) {
            String garansi;
            if (JRBGaransiYa.isSelected()) {
                garansi = "Ya";
            } else {
                garansi = "Tidak";
            }
            Update update = new LSubProces.Update();
            boolean ubah = update.Ubah("UPDATE `tbmbarang` SET `IdKategoriBarang`=(SELECT `IdKategoriBarang` FROM `tbmkategoribarang` AS A JOIN `tbmjenisbarang` AS B ON A.`IdJenisBarang`=B.`IdJenisBarang` WHERE `JenisBarang`='" + JCJenisBarang.getSelectedItem() + "' AND `KategoriBarang`='" + JCKategoriBarang.getSelectedItem() + "'), `NamaBarang`='" + JTNamaBarang.getText() + "', `Garansi`='" + garansi + "', `Satuan`='" + JTSatuan.getText() + "', `Keterangan`='" + JTKeterangan.getText() + "' WHERE `IdBarang`=" + idEdit, "Ubah Data Master Barang", this);
            if (ubah) {
                GlobalVar.Var.editMasterBarang.dispose();
                GlobalVar.Var.listMasterBarang.load();
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup BGGaransi;
    private KomponenGUI.JbuttonF JBJenisBarang;
    private KomponenGUI.JbuttonF JBKategoriBarang;
    private KomponenGUI.JbuttonF JBKembali;
    private KomponenGUI.JbuttonF JBTambah;
    private KomponenGUI.JbuttonF JBTambahTutup;
    private KomponenGUI.JbuttonF JBUbah;
    public KomponenGUI.JcomboboxF JCJenisBarang;
    public KomponenGUI.JcomboboxF JCKategoriBarang;
    private KomponenGUI.JlableF JLGaransi;
    private KomponenGUI.JlableF JLGaransi2;
    private KomponenGUI.JlableF JLJenisBarang;
    private KomponenGUI.JlableF JLJenisBarang2;
    private KomponenGUI.JlableF JLKategoriBarang;
    private KomponenGUI.JlableF JLKategoriBarang2;
    private KomponenGUI.JlableF JLKeterangan;
    private KomponenGUI.JlableF JLKeterangan2;
    private KomponenGUI.JlableF JLNamaBarang;
    private KomponenGUI.JlableF JLNamaBarang2;
    private KomponenGUI.JlableF JLSatuan;
    private KomponenGUI.JlableF JLSatuan2;
    private KomponenGUI.JRadioButtonF JRBGaransiTidak;
    private KomponenGUI.JRadioButtonF JRBGaransiYa;
    private javax.swing.JScrollPane JSPKeterangan;
    private KomponenGUI.JTextAreaF JTKeterangan;
    private KomponenGUI.JtextF JTNamaBarang;
    private KomponenGUI.JtextF JTSatuan;
    // End of variables declaration//GEN-END:variables
}
